name = "habtrack"
compatibility_date = "2026-05-27"
main = "worker.js"

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = [ "/api/*" ]

[vars]
STRIPE_PUBLISHABLE_KEY = "pk_test_51TctSYHWIgUdUt81xYECQy12U2BSEcAAuLm9wraBUfStW8Vm5r3KEjiJdwcq4HjnelSR8BwIDnRQSefFoGRaXV2H00qf8ZVJ0l"
