name = "habtrack"
compatibility_date = "2026-05-27"
main = "worker.js"
workers_dev = true

routes = [
  { pattern = "habtrack.shop", zone_name = "habtrack.shop", custom_domain = true },
  { pattern = "www.habtrack.shop", zone_name = "habtrack.shop", custom_domain = true },
  { pattern = "thankyou.habtrack.shop", zone_name = "habtrack.shop", custom_domain = true }
]

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = [ "/", "/index.html", "/api/*", "/checkout/checkout.js" ]

[vars]
STRIPE_PUBLISHABLE_KEY = "pk_live_51TctSYHWIgUdUt81WJpIZZk0WFQP4ZA6tlL7yIsIZFy2xeCkxwRIuSrKJqexZDH5UpepQGLLQuX8qKND44WSydjX00RA2fy9pC"
